name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        pip install pytest-cov
        pytest --cov=wtosbc tests/ --cov-report=xml
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: ./coverage.xml
        fail_ci_if_error: true
